New category Election and two additions to the Editor category
IgniteUI/material-icons-extended pull request #24
Opened 2020-10-28 12:39 UTC by sdimchevski

- New **Election** category with 14 new icons added
- New **exact match** and **match** icons added to the Editor category

2020-10-29 10:08 UTC, StefanIvanov requested changes

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/exact-match-1.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.683,9a7,7,0,1,1,0,6H8.025a5,5,0,1,0,0-6ZM3.79,7.047a9.6,9.6,0,1,1,0,9.906L2.055,18.688a12,12,0,1,0,0-13.376ZM0,14.914l1.432,1.4
Remove this one as it is a duplicate of the one below exact-match.svg

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/results-by-candidates.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M11,12.315V2.062a9.985,9.985,0,1,0,5.865,18.631ZM7.3,
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-ca.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M8.494,3.285,7.143,8.632l6.338,8.946L14,19.121l-1.247
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-fl.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M7.927,2.455l.616.909,5.389-.606s.616.606,1.078.454S1
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-ny.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M2.115,2.758H3.376L5.662,6.772V2.758H6.783V8.516H5.58
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-party-democratic.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M19,8H11.189L7.766,4.753S8.024,2,7.08,2c-.686,0-.943,
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-party-green.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M21.361,10.458,13.542,2.639a2.18,2.18,0,0,0-3.084,0L2
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-party-libertarian.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M21.9,9.034C21.47,8.7,21,8,19.021,9a3.113,3.113,0,0,1
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-party-republican.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M23,17v1a3,3,0,0,1-6,0V15.5a.5.5,0,0,0-.5-.5h-1a.5.5,
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-29 10:08 UTC, StefanIvanov commented on src/svgs/usa-tx.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.a{fill:none;}</style></defs><path class="a" d="M0,0H24V24H0Z"/><path d="M10.987,2l3.237.235V4.742l1.618.744,2.329.744,1.5-.31
I think we should remove this part: <defs><style>.a{fill:none;}</style></defs>

2020-10-30 11:33 UTC, StefanIvanov requested changes
Now you only need to remove src/svgs/exact-match-1.svg

2020-10-30 11:54 UTC, StefanIvanov approved these changes

2020-11-02 07:44 UTC, simeonoff approved these changes

2020-11-20 12:12 UTC, StefanIvanov approved these changes

2020-11-23 11:30 UTC, simeonoff approved these changes

2020-11-23 11:31 UTC, merged